---
title: "204_a2"
author: "Bren Comms Department"
date: "4/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Attach packages
library(tidyverse)
library(janitor)
library(plotly)
library(kableExtra)
library(dplyr)
library(here)
library(ggbeeswarm)
library(car)
library(plotly)
library(effsize)

# Read in the original data
data_raw <- read_csv("HW2_Data.csv")

em_A = 170
em_B = 200
em_C = 230
em_D = 300
```

```{r}
## NUMBER 1 FOR A

ggplot(data_raw, aes(x = Abatement, y = MC_A))+
  geom_point()+
  stat_smooth(method = "lm", formula = y ~ x, col = "red")

lm(formula = MC_A ~ Abatement, data = data_raw)
```

A = 170
y = mx + b

m = 0.513
b = 1.663

a r^2 = 0.7725
b r^2 = 0.7102
c r^2 = 0.8954
d r^2 = 0.8261

A: 
Abatement y = 0.513x + 1.663
Pollution y = 88.8725 - 0.513x

```{r}
## NUMBER 2 FOR A

#y point
y_a = 0.513*(em_A) + 1.663
a_dem_int <- y_a

#slope
slope_dem_a = ((y_a-0)/(0-em_A))
a_dem_slop <- slope_dem_a
a_dem_slop

#Demand curve
a_dem_curv <- function(x){88.8725 - 0.513*x}

#plot demand curves
curve(a_dem_curv, from = 0, to = 200, xlim = c(0,300), xaxs = "i", ylim = c(0,200), yaxs = "i",yaxs = "i", xlab = "Carbon Emitted (Tons)", ylab = "Price ($) per Ton")

# RENATA REWRITE

# y_a = 88.8725 - 0.513x

```


```{r}
## NUMBER 1 FOR B

ggplot(data_raw, aes(x = Abatement, y = MC_B))+
  geom_point()+
  stat_smooth(method = "lm", formula = y ~ x, col = "red")

lm(formula = MC_B ~ Abatement, data = data_raw)
```

y = mx + b

slope = 0.3918  
y-int = 8.7853

B
Abatement y = 0.3918x + 8.7853
Pollution y = 87.1453 - 0.3918x

```{r}
## NUMBER 2 FOR B

#y point
y_b = 0.3918*(em_B) + 8.7853
b_dem_int <- y_b

#slope
slope_dem_b = ((y_b-0)/(0-em_B))
b_dem_slop <- slope_dem_b

#Demand curve
b_dem_curv <- function(x){x*b_dem_slop + b_dem_int}

#plot demand curves
curve(b_dem_curv, from = 0, to = 200, xlim = c(0,300), xaxs = "i", ylim = c(0,200), yaxs = "i",yaxs = "i", xlab = "Carbon Emitted (Tons)", ylab = "Price ($) per Ton")

# RENATA REWRITE

# y = 87.1453 - 0.3918p

# what renata got y_b = 87.14129 - 0.3918p

test <- function(x){87.1453 - 0.3918*x}

curve(test, from = 0, to = 200, xlim = c(0,300), xaxs = "i", ylim = c(0,200), yaxs = "i",yaxs = "i", xlab = "Carbon Emitted (Tons)", ylab = "Price ($) per Ton")
```


```{r}
## NUMBER 1 FOR C

ggplot(data_raw, aes(x = Abatement, y = MC_C))+
  geom_point()+
  stat_smooth(method = "lm", formula = y ~ x, col = "red")

lm(formula = MC_C ~ Abatement, data = data_raw)
```

y = mx + b

slope = 1.13   
y-int = -26.81

C
Abatement y = 1.13x - (26.81)
Pollution y = 233.09 - 1.13x

```{r}
## NUMBER 2 FOR C

#y point
y_c = 1.13*(em_C) - (26.81)
c_dem_int <- y_c

#slope
slope_dem_c = ((y_c-0)/(0-em_C))
c_dem_slop <- slope_dem_c

#Demand curve
c_dem_curv <- function(x){233.09 - 1.13*x}

#plot demand curves
curve(c_dem_curv, from = 0, to = 300, xlim = c(0,250), xaxs = "i", ylim = c(0,250), yaxs = "i",yaxs = "i", xlab = "Carbon Emitted (Tons)", ylab = "Price ($) per Ton")
curve(test, from = 0, to = 200, xlim = c(0,300), xaxs = "i", ylim = c(0,200), yaxs = "i",yaxs = "i", xlab = "Carbon Emitted (Tons)", ylab = "Price ($) per Ton")

# RENATA REWRITE

# y_c = 233.09 - 1.13p



```


```{r}
#1D
ggplot(data_raw, aes(x = Abatement, y = MC_D))+
  geom_point()+
  stat_smooth(method = "lm", formula = y ~ x, col = "red")

lm(formula = MC_D ~ Abatement, data = data_raw)
```

y = mx + b

slope = 0.5535
y-int = -12.2103

D
Abatement y = 0.5535x - 12.2103
Pollution y = 153.8397 - 0.5535x

```{r}
## NUMBER 2 FOR D

#y point
y_d = 0.5535*(em_D) - 12.2103
d_dem_int <- y_d

# y = -0.512799*x + 153.8397

#slope
slope_dem_d = ((y_d-0)/(0-em_D))
d_dem_slop <- slope_dem_d

#Demand curve
d_dem_curv <- function(x){x*d_dem_slop + d_dem_int}

#plot demand curves
curve(d_dem_curv, from = 0, to = 300, xlim = c(0,350), xaxs = "i", ylim = c(0,200), yaxs = "i",yaxs = "i", xlab = "Carbon Emitted (Tons)", ylab = "Price ($) per Ton")

# RENATA REWRITE

# y_d = 153.8397 - 0.5535x

```

PART 3

```{r}
##Part 3A

# sectors a b and c, now have to produce 100 tons of carbon


#A
0.513*(100) + 1.663
# (100, 52.963)
# (100, 0)
# (0, 1.663)

# Cost to sector A : $814.45


y_b = 0.3918*(em_B) + 8.7853

y_c = 1.13*(em_C) - (26.81)


##Part 3B
56.05997*300
# 16817.99 -- tax revenue

##Part 3C

# x = 5.386y - 1.939
# y = (x + 1.939)/5.386
y_ag = (300 + 1.939)/5.386
# y_ag : market price OR tax = 56.05997

A_MC_eq <- (y_ag - 1.663)/0.513
# 106.037

B_MC_eq <- (y_ag - 8.7853)/0.3918
# 120.6602

C_MC_eq <- (y_ag + 26.81)/1.13
# 73.33626

MC_eq_agg <- A_MC_eq + B_MC_eq + C_MC_eq


###

y = 0.513x

```

PART 3
a. 
b.
c. 

```{r}
# 3a - for A

y_3a_a = 0.513*(100) + 1.663
# y_3a_a = 52.963

((0.5)*(100)*(52.963-1.663)) + ((1.663)*(100))
# = 2731.3

###

# 3a - for B

y_3a_b = 0.3918*(100) + 8.7853
# y_3a_b = 47.9653
((0.5)*(100)*(47.9653-8.7853)) + ((8.7853)*(100))
# = 2837.53

###

# 3a - for C

y_3a_c = 1.13*(100) - (26.81)
# y_3a_c = 86.19

((0.5)*(100-23.7257)*(86.19)) - ((1/2)*(26.81)*(23.7257))
# = 2968.998 

# 2731.3 + 2837.53 + 3287.041 = 8855.871

# Y_AG = (x + 1.9387) / 5.3866
(x / 5.3866) + (0.3599)
Y_AG = (300 + 1.9387) / 5.3866
# Y_AG = 56.05367

((0.5)*(300)*(56.05367-0.3599)) + (0.3599*300)
# 8462.035

2968.998 + 2731.3 + 2837.53
# 8537.828



###

(56.05367 - 1.663)/0.513
# 106.0247

(56.05367 - 8.7853)/0.3918
# 120.6441

(56.05367 + 26.81)/1.13
# 73.33068

73.33068 + 120.6441 + 106.0247

```
