---
title: "tri2"
author: "Peyton Moore"
date: "4/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#Attach packages
library(tidyverse)
library(janitor)
library(plotly)
library(kableExtra)
library(dplyr)
library(here)
library(ggbeeswarm)
library(car)
library(plotly)
library(effsize)

# Read in the original data
data_raw <- read_csv("HW2_Data.csv")

em_A = 170
em_B = 200
em_C = 230
em_D = 300
```

```{r}
## NUMBER 1 FOR A

ggplot(data_raw, aes(x = Abatement, y = MC_A))+
  geom_point()+
  stat_smooth(method = "lm", formula = y ~ x, col = "red")

lm(formula = MC_A ~ Abatement, data = data_raw)
```

A = 170
y = mx + b

m = 0.513
b = 1.663

```{r}
## NUMBER 2 FOR A

#y point
y_a = 0.513*(em_A) + 1.663
a_dem_int <- y_a

#slope
slope_dem_a = ((y_a-0)/(0-em_A))
a_dem_slop <- slope_dem_a

#Demand curve
a_dem_curv <- function(x){x*a_dem_slop + a_dem_int}

#plot demand curves
curve(a_dem_curv, from = 0, to = 200, xlim = c(0,300), xaxs = "i", ylim = c(0,200), yaxs = "i",yaxs = "i", xlab = "Carbon Emitted (Tons)", ylab = "Price ($) per Ton")
```


```{r}
## NUMBER 1 FOR B

ggplot(data_raw, aes(x = Abatement, y = MC_B))+
  geom_point()+
  stat_smooth(method = "lm", formula = y ~ x, col = "red")

lm(formula = MC_B ~ Abatement, data = data_raw)
```

y = mx + b

slope = 0.3918  
y-int = 8.7853

```{r}
## NUMBER 2 FOR B

#y point
y_b = 0.3918*(em_B) + 8.7853
b_dem_int <- y_b

#slope
slope_dem_b = ((y_b-0)/(0-em_B))
b_dem_slop <- slope_dem_b

#Demand curve
b_dem_curv <- function(x){x*b_dem_slop + b_dem_int}

#plot demand curves
curve(b_dem_curv, from = 0, to = 200, xlim = c(0,300), xaxs = "i", ylim = c(0,200), yaxs = "i",yaxs = "i", xlab = "Carbon Emitted (Tons)", ylab = "Price ($) per Ton")
```


```{r}
## NUMBER 1 FOR C

ggplot(data_raw, aes(x = Abatement, y = MC_C))+
  geom_point()+
  stat_smooth(method = "lm", formula = y ~ x, col = "red")

lm(formula = MC_C ~ Abatement, data = data_raw)
```

y = mx + b

slope = 1.13   
y-int = -26.81

```{r}
## NUMBER 2 FOR C

#y point
y_c = 1.13*(em_C) - (26.81)
c_dem_int <- y_c

#slope
slope_dem_c = ((y_c-0)/(0-em_C))
c_dem_slop <- slope_dem_c

#Demand curve
c_dem_curv <- function(x){x*c_dem_slop + c_dem_int}

#plot demand curves
curve(c_dem_curv, from = 0, to = 300, xlim = c(0,250), xaxs = "i", ylim = c(0,250), yaxs = "i",yaxs = "i", xlab = "Carbon Emitted (Tons)", ylab = "Price ($) per Ton")

```


```{r}
#1D
ggplot(data_raw, aes(x = Abatement, y = MC_D))+
  geom_point()+
  stat_smooth(method = "lm", formula = y ~ x, col = "red")

lm(formula = MC_D ~ Abatement, data = data_raw)
```

y = mx + b

slope = 0.5535  
y-int = -12.2103

```{r}
## NUMBER 2 FOR D

#y point
y_d = 0.5535*(em_D) - 12.2103
d_dem_int <- y_d

y = -0.512799*x + 153.8397

#slope
slope_dem_d = ((y_d-0)/(0-em_D))
d_dem_slop <- slope_dem_d

#Demand curve
d_dem_curv <- function(x){x*d_dem_slop + d_dem_int}

#plot demand curves
curve(d_dem_curv, from = 0, to = 300, xlim = c(0,350), xaxs = "i", ylim = c(0,200), yaxs = "i",yaxs = "i", xlab = "Carbon Emitted (Tons)", ylab = "Price ($) per Ton")

```


```{r}
data_longer <- pivot_longer(data_raw, MC_A:MC_D, names_to="sector", values_to = "mc")

ggplot(data = data_longer, aes(y = mc,
                                   x = Abatement))+
  geom_blank(mapping = NULL)+
  geom_abline(intercept = 1.663, slope = 0.513, color = "blue")+
  annotate("text", x = 310, y = 170, label = "A", color = "blue")+
  #A
  geom_abline(intercept = 8.785, slope = 0.3918, color = "forestgreen")+
  annotate("text", x = 390, y = 170, label = "B", color = "forestgreen")+
  #B
  geom_abline(intercept = -26.81, slope = 1.13, color = "red") +
  annotate("text", x = 185, y = 170, label = "C", color = "red")+
  #C
  geom_abline(intercept = -12.2103, slope = 0.55, color = "purple")+
  annotate("text", x = 350, y = 170, label = "D", color = "purple")+
  #D
  geom_abline(intercept = 0.3597, slope = 0.1856, color = "black")+
  annotate("text", x = 550, y = 125, label = "Country X", color = "black")+
  annotate("text", x = 550, y = 115, label = "Aggreagte", color = "black")+
  # Country X aggregate = 0.1856x + 0.3597
  geom_abline(intercept = -2.9164, slope = 0.1445, color = "orange")+
  annotate("text", x = 550, y = 65, label = "All Country", color = "orange")+
  annotate("text", x = 550, y = 55, label = "Aggregate", color = "orange")+
  # All country aggregate = 0.1445x - 2.9164
  geom_vline(xintercept = 600, linetype="dashed")+
  theme_classic()+
  scale_x_continuous(expand = c(0,0),
                     limits = c(0,610))+
  scale_y_continuous(expand = c(0,0))+
  labs(title = "Marginal Cost of Abatement in Each Sector", 
       x = "Tons of CO2 Abated", 
       y = "USD ($)")
  #FINALIZE GRAPH 
  
```


```{r}
ggplot(data = data_longer, aes(y = mc,
                                   x = Abatement))+
  geom_blank(mapping = NULL)+
  geom_abline(intercept = 88.87, slope = -0.5227, color = "blue")+
  #A
  geom_abline(intercept = 87.1453, slope = -0.4357, color = "forestgreen")+
  #B
  geom_abline(intercept = 233.09, slope = -1.013, color = "red") +
  #C
  geom_abline(intercept = 81.2897, slope = -0.2709, color = "purple")+
  #D
  theme_classic()+
  scale_x_continuous(expand = c(0,0),
                     limits = c(0,310))+
  scale_y_continuous(expand = c(0,0))+
  labs(title = "Demand for Carbon in Each Sector", 
       x = "Tons of CO2", 
       y = "USD ($)")
```

```{r}
ggplot(data = data_longer, aes(y = mc,
                                   x = Abatement))+
  geom_blank(mapping = NULL)+
  geom_abline(intercept = -12.2103, slope = 0.55, color = "purple")+
  annotate("text", x = 350, y = 170, label = "D", color = "purple")+
  #D
  geom_abline(intercept = -2.9164, slope = 0.1445, color = "orange")+
  annotate("text", x = 550, y = 65, label = "All Country", color = "orange")+
  annotate("text", x = 550, y = 55, label = "Aggregate", color = "orange")+
  # All country aggregate = 0.1445x - 2.9164
  geom_vline(xintercept = 300, color = "violet", linetype="dashed")+
  # vertical @ 300
  geom_vline(xintercept = 600, linetype="dashed")+
  # vertical @ 600
  geom_vline(xintercept = 126.46, linetype="dashed")+
  geom_abline(intercept = 83.7836, slope = 0, color = "black", linetype = "dashed")+
  # horizontal intercept of 600 cap
  geom_abline(intercept = 153.8397, slope = 0, color = "violet", linetype = "dashed")+
  # horizontal intercept of 300 cap
  geom_abline(intercept = 153.84, slope = -0.554, color = "violet")+
  #D - pollution curve (y = 153.84 - 0.554x)
  theme_classic()+
  scale_x_continuous(expand = c(0,0),
                     limits = c(0,610))+
  scale_y_continuous(expand = c(0,0))+
  labs(title = "Marginal Cost of Abatement in Each Sector", 
       x = "Tons of CO2 Abated", 
       y = "USD ($)")
  #FINALIZE GRAPH 

#y_d = 0.5535x - 12.2103
0.5535*(300) - 12.2103
# y = 153.8397

# y_ag = 0.1445x-2.9164
0.1445*(600) - 2.9164
# y = 83.7836

# Calculating Q for CS
# D demand -- x = (153.84 - y)/0.554 ; using x = 83.78
(153.84 - 83.78)/0.554
# y = 126.4621

# CS from integrating with Country X
# CS = (1/2)*(Q)*(Pmax - Pd)
Pmax = 153.84; Pd = 83.78; Q = 126.46
(1/2)*(Q)*(Pmax - Pd)
# CA = 4429.894

```

